name: Lenna
# Make sure to change what triggers your action based on your needs
on:
  schedule:
    - cron: "0 22 * * *" # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:

# Do not fucking delete Thumbnail, URLS or the author shit, IT WILL FUCK EVERYTHING OVER
# It's just one of those "It just works" coding shit that trying to improve the codes BREAKS EVERYTHING
  
jobs:
  # ID of our job
  webhook-request:
    # OS to run our job on
    runs-on: ubuntu-latest
    steps:
    - name: Send to Discord 1
      run: |
        RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
        "username": "Lenna",
        "content": "@everyone",
        "embeds": [
          {
            "type": "rich",
            "title": "Daily Login Reminder~",
            "description": "Hello Commander, Lenna here! I need to remind you to login and do your dailys!",
            "color": 2123412,
            "thumbnail": {
              "url": "" 
            },
            "author": {
            },
            "url": "" 
          },
          {
            "type": "rich",
            "title": "Daily Platoon Activitys!",
            "description": "Your Platoon Activity Rewards are very important make sure to complete them and GFS.",
            "color": 2123412,
            "thumbnail": {
              "url": ""
            },
            "author": {
            },
            "url": ""
          }
        ]
        }' ${{ secrets.DISCORD_WEBHOOK }})
        echo "Webhook server response: $RESPONSE"
  
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
