name: Reminder
# Make sure to change what triggers your action based on your needs
on:
  schedule:
    - cron: "0 22 * * *" # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:
  
jobs:
  # ID of our job
  webhook-request:
    # OS to run our job on
    runs-on: ubuntu-latest
    steps:
    - name: Send a request to webhook
      run: |
        RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
        "username": "Lenna",
        "content": "@everyone",
        "embeds": [
          {
            "type": "rich",
            "title": "Daily Login Reminder!~",
            "description": "Hey Commander, Lenna here! I need to remind you all to login and do your dailys!",
            "color": 2123412,
        }
        ]
        }' ${{ secrets.DISCORD_WEBHOOK }})
        echo "Webhook server response: $RESPONSE"
