name: Colphne
# Make sure to change what triggers your action based on your needs
on:
  schedule:
    - cron: "0 22 * * *" # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:

# Do not fucking delete Thumbnail, URLS or the author shit, IT WILL FUCK EVERYTHING OVER
# It's just one of those "It just works" coding shit that trying to improve the codes BREAKS EVERYTHING
  
jobs:
  # ID of our job
  webhook-request:
    # OS to run our job on
    runs-on: ubuntu-latest
    steps:
    - name: Send to Discord 1
      run: |
        RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
        "username": "Colphne",
        "content": "Don't forget me!",
        "embeds": [
          {
            "type": "rich",
            "title": "Daily BP Reminder~",
            "description": "Don't forget to complete your Voyage logs~",
            "color": 2123412,
            "thumbnail": {
              "url": "" 
            },
            "author": {
            },
            "url": "" 
          },
          {
            "type": "rich",
            "title": "Daily Platoon Activites!",
            "description": "The most important thing for us as a Platoon is to log in and get the highscores we can durring GSF, so log in and do both that and the platoon Dailys!",
            "color": 2123412,
            "thumbnail": {
              "url": ""
            },
            "author": {
            },
            "url": ""
          }
        ]
        }' ${{ secrets.DISCORD_WEBHOOK2 }})
        echo "Webhook server response: $RESPONSE"
  
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
